openapi: "3.0.0"
info:
  version: 1.0.0
  title: Ola app
  description: TODO
servers:
  - url: https://localhost:8080/api
    variables:
      hostname:
        default: localhost
security:
  - bearerAuth: []
paths:
  /users/{id}:
    get:
      description: Get user
      operationId: get user by id
      parameters:
        - name: id
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - email
      properties:
        email:
          type: string


    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string


